"""Tests for skill extractors.

Tests PythonExtractor, ClaudeSkillImporter, and ExampleBasedCreator.
"""

import os
import textwrap

import pytest
import yaml

from contextledger.backends.llm.stub import StubLLMClient
from contextledger.skill.extractor import (
    ClaudeSkillImporter,
    ExampleBasedCreator,
    PythonExtractor,
)


# ---------------------------------------------------------------------------
# Helpers — sample Python files
# ---------------------------------------------------------------------------

SAMPLE_PYTHON = textwrap.dedent("""\
    \"\"\"Pipeline that extracts entities and synthesises reports.\"\"\"

    def extract_entities(raw_text: str) -> dict:
        \"\"\"Extract entity mentions from raw text.\"\"\"
        return {"entities": [{"type": "finding", "value": raw_text}]}

    def analyse_results(entities: list) -> dict:
        \"\"\"Analyse extracted entities for patterns.\"\"\"
        processed = extract_entities("test")
        return {"results": processed}

    def synthesise_report(analysis: dict) -> dict:
        \"\"\"Synthesise a report from analysis results.\"\"\"
        findings = analyse_results(analysis)
        return {"findings": findings}

    def helper_function(x):
        \"\"\"A helper that should NOT be picked up.\"\"\"
        return x + 1

    def filter_low_confidence(items: list) -> list:
        \"\"\"Filter out items below confidence threshold.\"\"\"
        return [i for i in items if i.get("confidence", 0) > 0.5]
""")

SAMPLE_PYTHON_NO_CANDIDATES = textwrap.dedent("""\
    \"\"\"A module with no extraction functions.\"\"\"

    def add(a, b):
        return a + b

    def multiply(a, b):
        return a * b
""")

SAMPLE_SKILL_MD = textwrap.dedent("""\
    # Frontend Design Skill

    This skill helps with frontend component design.
    It extracts component structures, design patterns, and accessibility findings
    from coding sessions.

    ## When to use
    - Reviewing React component architecture
    - Identifying accessibility issues
    - Documenting design decisions

    ## Entity types
    - Components
    - Design patterns
    - Accessibility findings
""")


# ---------------------------------------------------------------------------
# PythonExtractor tests
# ---------------------------------------------------------------------------

class TestPythonExtractor:

    @pytest.fixture
    def extractor(self):
        return PythonExtractor()

    @pytest.fixture
    def sample_file(self, tmp_path):
        f = tmp_path / "my_pipeline.py"
        f.write_text(SAMPLE_PYTHON, encoding="utf-8")
        return str(f)

    @pytest.fixture
    def empty_file(self, tmp_path):
        f = tmp_path / "empty_pipeline.py"
        f.write_text(SAMPLE_PYTHON_NO_CANDIDATES, encoding="utf-8")
        return str(f)

    def test_python_extractor_identifies_extraction_functions(self, extractor, sample_file):
        """PythonExtractor should find functions with candidate keywords."""
        result = extractor.extract(sample_file)
        parsed = yaml.safe_load(result)

        node_ids = [n["id"] for n in parsed["synthesis"]["dag"]["nodes"]]
        assert "extract_entities" in node_ids
        assert "analyse_results" in node_ids
        assert "synthesise_report" in node_ids
        assert "filter_low_confidence" in node_ids
        # helper_function should NOT be found
        assert "helper_function" not in node_ids

    def test_python_extractor_infers_dag_dependencies(self, extractor, sample_file):
        """PythonExtractor should detect calls between candidate functions."""
        result = extractor.extract(sample_file)
        parsed = yaml.safe_load(result)

        nodes_by_id = {n["id"]: n for n in parsed["synthesis"]["dag"]["nodes"]}

        # analyse_results calls extract_entities
        assert "extract_entities" in nodes_by_id["analyse_results"]["depends_on"]

        # synthesise_report calls analyse_results
        assert "analyse_results" in nodes_by_id["synthesise_report"]["depends_on"]

        # extract_entities calls nothing (in candidates)
        assert nodes_by_id["extract_entities"]["depends_on"] == []

    def test_python_extractor_generates_valid_profile_stub(self, extractor, sample_file):
        """PythonExtractor output should be valid YAML with required sections."""
        result = extractor.extract(sample_file)

        # Should contain header comments
        assert "Auto-generated by" in result
        assert "REVIEW" in result

        # Should be valid YAML
        parsed = yaml.safe_load(result)
        assert parsed is not None

        # Required top-level keys
        assert "name" in parsed
        assert "version" in parsed
        assert "extraction" in parsed
        assert "synthesis" in parsed
        assert "session_context" in parsed

        # Profile name derived from filename
        assert parsed["name"] == "my-pipeline-skill"
        assert parsed["version"] == "1.0.0"

        # Extraction section
        assert "entities" in parsed["extraction"]
        assert "sources" in parsed["extraction"]

        # Session context
        assert parsed["session_context"]["mode"] == "skill_versioning"
        assert parsed["session_context"]["cmv_enabled"] is True

    def test_python_extractor_handles_no_candidates_gracefully(self, extractor, empty_file):
        """When no candidate functions are found, still produce valid YAML."""
        result = extractor.extract(empty_file)
        parsed = yaml.safe_load(result)

        assert parsed is not None
        assert parsed["name"] == "empty-pipeline-skill"
        # DAG should have no nodes
        assert parsed["synthesis"]["dag"]["nodes"] == []
        # Entities should still have defaults
        assert len(parsed["extraction"]["entities"]) > 0

    def test_python_extractor_infers_node_types(self, extractor, sample_file):
        """PythonExtractor should map function name keywords to correct node types."""
        result = extractor.extract(sample_file)
        parsed = yaml.safe_load(result)

        nodes_by_id = {n["id"]: n for n in parsed["synthesis"]["dag"]["nodes"]}

        assert nodes_by_id["extract_entities"]["type"] == "extraction"
        assert nodes_by_id["analyse_results"]["type"] == "reasoning"
        assert nodes_by_id["synthesise_report"]["type"] == "synthesis"
        assert nodes_by_id["filter_low_confidence"]["type"] == "filter"


# ---------------------------------------------------------------------------
# ClaudeSkillImporter tests
# ---------------------------------------------------------------------------

class TestClaudeSkillImporter:

    @pytest.fixture
    def llm(self):
        return StubLLMClient()

    @pytest.fixture
    def importer(self, llm):
        return ClaudeSkillImporter(llm)

    @pytest.fixture
    def skill_md_file(self, tmp_path):
        skill_dir = tmp_path / "frontend-design"
        skill_dir.mkdir()
        f = skill_dir / "SKILL.md"
        f.write_text(SAMPLE_SKILL_MD, encoding="utf-8")
        return str(f)

    def test_claude_skill_importer_wraps_skill_md(self, importer, skill_md_file):
        """ClaudeSkillImporter should reference the SKILL.md in refs."""
        result = importer.import_skill(skill_md_file)
        parsed = yaml.safe_load(result)

        assert parsed is not None
        # The SKILL.md path should be in refs
        assert skill_md_file in parsed["refs"]

        # Should have standard DAG structure
        node_ids = [n["id"] for n in parsed["synthesis"]["dag"]["nodes"]]
        assert "extract_entities" in node_ids
        assert "build_relationships" in node_ids
        assert "synthesise_findings" in node_ids

        # Profile name derived from parent directory
        assert parsed["name"] == "frontend-design-skill"

        # Should have session context
        assert parsed["session_context"]["mode"] == "skill_versioning"
        assert parsed["session_context"]["cmv_enabled"] is True

    def test_claude_skill_importer_infers_entities_from_content(self, importer, skill_md_file):
        """ClaudeSkillImporter should use LLM to infer entities from SKILL.md."""
        result = importer.import_skill(skill_md_file)
        parsed = yaml.safe_load(result)

        # The StubLLMClient returns entities when it sees "extract" and "entities"
        # in the prompt. Our prompt contains both keywords.
        assert "extraction" in parsed
        assert "entities" in parsed["extraction"]
        assert len(parsed["extraction"]["entities"]) > 0

        # Should also have sources
        assert "sources" in parsed["extraction"]

        # Header should mention the import source
        assert "Imported from" in result


# ---------------------------------------------------------------------------
# ExampleBasedCreator tests
# ---------------------------------------------------------------------------

class TestExampleBasedCreator:

    @pytest.fixture
    def llm(self):
        return StubLLMClient()

    @pytest.fixture
    def creator(self, llm):
        return ExampleBasedCreator(llm)

    @pytest.fixture
    def examples(self):
        return [
            {
                "session_excerpt": "The users table has no index on email column.",
                "finding": {"type": "missing_index", "table": "users", "column": "email"},
            },
            {
                "session_excerpt": "Query on orders.created_at takes 4.2 seconds.",
                "finding": {"type": "slow_query", "table": "orders", "column": "created_at"},
            },
            {
                "session_excerpt": "The products table is missing a foreign key to categories.",
                "finding": {"type": "missing_fk", "table": "products", "ref_table": "categories"},
            },
        ]

    def test_example_based_creator_infers_extraction_rules(self, creator, examples):
        """ExampleBasedCreator should produce valid YAML from examples."""
        result = creator.create(examples)
        parsed = yaml.safe_load(result)

        assert parsed is not None
        assert "name" in parsed
        assert "extraction" in parsed
        assert "entities" in parsed["extraction"]
        assert len(parsed["extraction"]["entities"]) > 0

        # Should have synthesis DAG
        assert "synthesis" in parsed
        node_ids = [n["id"] for n in parsed["synthesis"]["dag"]["nodes"]]
        assert "extract_entities" in node_ids

        # Should have session context
        assert parsed["session_context"]["mode"] == "skill_versioning"

        # Header should mention number of examples
        assert "3 examples" in result

    def test_example_based_creator_requires_at_least_3_examples(self, creator):
        """ExampleBasedCreator should raise ValueError with fewer than 3 examples."""
        with pytest.raises(ValueError, match="(?i)at least 3"):
            creator.create([
                {"session_excerpt": "test", "finding": {"type": "test"}},
                {"session_excerpt": "test2", "finding": {"type": "test2"}},
            ])

        # Zero examples should also fail
        with pytest.raises(ValueError, match="(?i)at least 3"):
            creator.create([])

        # One example should also fail
        with pytest.raises(ValueError, match="(?i)at least 3"):
            creator.create([{"session_excerpt": "x", "finding": {}}])
